// game/src/routes/stats/SingleGameStats.svelte
<script lang="ts">
	import type { IStats } from '$lib/types';
	import StatsGraph from './StatsGraph.svelte';
	import StatsRow from './StatsRow.svelte';

	interface IProps {
		numberOfGames: number;
		title: string;
		maxWidth: number;
		stats: IStats;
	}

	const { numberOfGames, title, maxWidth, stats }: IProps = $props();

	const { finishCounts, ...rest } = $derived(stats);
</script>

<div class="game-stats">
	<h2>{title}</h2>
	<StatsRow stats={rest} {maxWidth} />
	<StatsGraph {numberOfGames} {finishCounts} {maxWidth} />
</div>

<style>
	.game-stats {
		display: flex;
		flex-direction: column;
		align-items: center;
		width: 100%;
	}
</style>

// game/components/SingleGameStats.tsx
import { StyleSheet, View } from "react-native";

import { selectGameStats, useGameSelector } from "@/store";
import { StatsGraph } from "./StatsGraph";
import { StatsRow } from "./StatsRow";
import { ThemedText } from "./ThemedText";

interface IProps {
  numberOfGames: number;
  title: string;
  maxWidth: number;
}

export function SingleGameStats(props: IProps) {
  const { numberOfGames, title, maxWidth } = props;

  const stats = useGameSelector((state) =>
    selectGameStats(state, numberOfGames),
  );

  const { finishCounts, ...rest } = stats;

  return (
    <View style={styles.container}>
      <ThemedText className="!font-nunitoBold !text-2xl">{title}</ThemedText>
      <StatsRow stats={rest} maxWidth={maxWidth} />
      <StatsGraph
        numberOfGames={numberOfGames}
        finishCounts={finishCounts}
        maxWidth={maxWidth}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
  },
});
