// game/app/stats.tsx
import { ScrollView, StyleSheet, useWindowDimensions } from "react-native";

import GradientBackgroundView from "@/components/GradientBackgroundView";
import { SingleGameStats } from "@/components/SingleGameStats";
import { GestureHandlerRootView } from "react-native-gesture-handler";

const gameModes = [
  ["Classic", 1],
  ["Duo", 2],
  ["Quad", 4],
] as [string, number][];

export default function Stats() {
  const { width: screenWidth } = useWindowDimensions();

  const maxWidth = Math.min(screenWidth, 500);

  return (
    <GradientBackgroundView style={styles.container}>
      <GestureHandlerRootView style={styles.gameWrapper}>
        <ScrollView
          contentContainerStyle={styles.stats}
          style={styles.scrollArea}
        >
          {gameModes.map(([title, numberOfGames]) => (
            <SingleGameStats
              key={numberOfGames}
              title={title}
              numberOfGames={numberOfGames}
              maxWidth={maxWidth}
            />
          ))}
        </ScrollView>
      </GestureHandlerRootView>
    </GradientBackgroundView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  gameWrapper: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  scrollArea: {
    height: "100%",
    width: "100%",
  },
  stats: {
    display: "flex",
    flexDirection: "column",
    gap: 64,
    padding: 32,
    alignItems: "center",
    justifyContent: "center",
  },
});

// game/src/routes/stats/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import SingleGameStats from './SingleGameStats.svelte';

	interface IProps {
		data: PageData;
	}

	let { data }: IProps = $props();

	const gameModes = [
		['Classic', 1],
		['Duo', 2],
		['Quad', 4]
	] as [string, number][];

	let screenWidth: number | null | undefined = $state();
	const maxWidth = $derived(Math.min(screenWidth ?? Infinity, 500));
</script>

<svelte:window bind:innerWidth={screenWidth} />

<div class="container">
	{#each gameModes as game}
		{@const title = game[0]}
		{@const numberOfGames = game[1]}
		<SingleGameStats
			{title}
			{numberOfGames}
			maxWidth={maxWidth}
			stats={data[numberOfGames]}
		/>
	{/each}
</div>

<style>
	.container {
		display: flex;
		flex-direction: column;
		gap: 64px;
		padding: 32px;
		align-items: center;
		justify-content: center;
		overflow-y: auto;
		text-align: center;
		height: 100%;
	}
</style>
